// swift-tools-version:6.0
// SliceAIKit - SliceAI 核心功能包，10 个 target 承载领域层、LLM、划词、快捷键、窗口、权限、设置、编排、能力、UI tokens
import PackageDescription

let swiftSettings: [SwiftSetting] = [
    .enableUpcomingFeature("ExistentialAny"),
    .enableExperimentalFeature("StrictConcurrency=complete"),
]

let package = Package(
    name: "SliceAIKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "SliceCore", targets: ["SliceCore"]),
        .library(name: "LLMProviders", targets: ["LLMProviders"]),
        .library(name: "SelectionCapture", targets: ["SelectionCapture"]),
        .library(name: "HotkeyManager", targets: ["HotkeyManager"]),
        .library(name: "Windowing", targets: ["Windowing"]),
        .library(name: "Permissions", targets: ["Permissions"]),
        .library(name: "SettingsUI", targets: ["SettingsUI"]),
        .library(name: "DesignSystem", targets: ["DesignSystem"]),
        .library(name: "Orchestration", targets: ["Orchestration"]),
        .library(name: "Capabilities", targets: ["Capabilities"]),
    ],
    targets: [
        .target(name: "SliceCore", swiftSettings: swiftSettings),
        .target(name: "Capabilities",
                dependencies: ["SliceCore"],
                exclude: ["README.md"],
                swiftSettings: swiftSettings),
        .target(name: "Orchestration",
                dependencies: ["SliceCore", "Capabilities"],
                exclude: ["README.md"],
                swiftSettings: swiftSettings),
        .target(name: "LLMProviders", dependencies: ["SliceCore"], swiftSettings: swiftSettings),
        .target(name: "SelectionCapture", dependencies: ["SliceCore"], swiftSettings: swiftSettings),
        .target(name: "HotkeyManager", dependencies: ["SliceCore"], swiftSettings: swiftSettings),
        .target(name: "DesignSystem",
                dependencies: ["SliceCore"],
                exclude: ["README.md"],
                resources: [.process("Colors/Resources/Assets.xcassets")],
                swiftSettings: swiftSettings),
        .target(name: "Windowing", dependencies: ["SliceCore", "DesignSystem"], swiftSettings: swiftSettings),
        .target(name: "Permissions", dependencies: ["SliceCore", "DesignSystem"], swiftSettings: swiftSettings),
        .target(name: "SettingsUI",
                dependencies: ["SliceCore", "LLMProviders", "HotkeyManager", "DesignSystem", "Permissions"],
                swiftSettings: swiftSettings),
        .testTarget(name: "SliceCoreTests",
                    dependencies: ["SliceCore"],
                    resources: [.copy("Fixtures")],
                    swiftSettings: swiftSettings),
        .testTarget(name: "OrchestrationTests", dependencies: ["Orchestration", "SliceCore", "Capabilities"], swiftSettings: swiftSettings),
        .testTarget(name: "CapabilitiesTests", dependencies: ["Capabilities", "SliceCore"], swiftSettings: swiftSettings),
        .testTarget(name: "LLMProvidersTests",
                    dependencies: ["LLMProviders", "SliceCore"],
                    resources: [.copy("Fixtures")],
                    swiftSettings: swiftSettings),
        .testTarget(name: "SelectionCaptureTests",
                    dependencies: ["SelectionCapture", "SliceCore"],
                    swiftSettings: swiftSettings),
        .testTarget(name: "HotkeyManagerTests",
                    dependencies: ["HotkeyManager", "SliceCore"],
                    swiftSettings: swiftSettings),
        .testTarget(name: "WindowingTests",
                    dependencies: ["Windowing", "SliceCore"],
                    swiftSettings: swiftSettings),
        .testTarget(name: "DesignSystemTests",
                    dependencies: ["DesignSystem", "SliceCore"],
                    swiftSettings: swiftSettings),
    ]
)
